#!/bin/bash
#Add new customers to file CustomerDetails in the format
#<E-mail Address>   <Name>   <Alias>   <Address>   <Telephone Number>
# check to see if CustomerDetails exists and if not then create it with the header
if grep -q "Address" CustomerDetails 
	then 
	echo CustomerDetails already exits 
else
	printf "\n %-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
fi
clear
# ANSI colour an formats moved to more readable variables names, can change echo colours
# the NONE is to turn off the format, echo -e enables the colour, may not use all of these
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo 
echo -e ${CYAN}_________________________________________________________________ ${NONE}
echo -e " ${CYAN}    _       _     _  ____          _                            ${NONE}"
echo -e " ${CYAN}   / \   __| | __| |/ ___|   _ ___| |_ ___  _ __ ___   ___ _ __ ${NONE}"
echo -e " ${CYAN}  / _ \ / _  |/ _  | |  | | | / __| __/ _ \|  _   _ \ / _ \ '__|${NONE}"
echo -e " ${CYAN} / ___ \ (_| | (_| | |__| |_| \__ \ || (_) | | | | | |  __/ |   ${NONE}"
echo -e " ${CYAN}/_/   \_\__,_|\__,_|\____\__,_|___/\__\___/|_| |_| |_|\___|_|   ${NONE}"                                            
echo -e ${CYAN}_________________________________________________________________ ${NONE}                                                           
echo -e ${CYAN}_________________________________________________________________ ${NONE}
echo Enter the following customer details 
echo
echo -e ${YELLOW}Name :${NONE}
read Name
echo
echo -e ${YELLOW}E-mail Address :${NONE}
read Email
echo
echo -e ${YELLOW}Alias :${NONE}
read Alias
echo
echo -e ${YELLOW}Address :${NONE}
read Address
echo
echo -e ${YELLOW}Telephone Number :${NONE}
read Telephone
echo
printf "\n %-30s %-8s %-8s %-20s %s" "$Email" "$Name" "$Alias" "$Address" "$Telephone" >> CustomerDetails
echo
echo -e "${RED}Do you wish to return to the Menu ?(y/n)${NONE}" 
read yesno
if  [[ $yesno = "y" ]]
	then 
	  ./Menu
else
	echo Goodbye
fi