#!/bin/bash
#find an existing customers from the file CustomerDetails 
#Enter a customer detail to find a contact
# check to see if CustomerDetails exists and if not then create it with the header
if grep -q "Address" CustomerDetails 
	then 
	echo CustomerDetails already exits 
else
	printf "\n %-30s %-8s %-8s %-20s %s" "<E-mail Address>" "<Name>" "<Alias>" "<Address>" "<Telephone Number>" >> CustomerDetails
fi
clear
# ANSI colour an formats moved to more readable variables names, can change echo colours
# the NONE is to turn off the format, echo -e enables the colour, may not use all of these
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo 
echo -e ${BLUE}__________________________________________________________________${NONE} 
echo -e "${BLUE} _____ _           _  ____          _                            ${NONE}"
echo -e "${BLUE}|  ___(_)_ __   __| |/ ___|   _ ___| |_ ___  _ __ ___   ___ _ __ ${NONE}"
echo -e "${BLUE}| |_  | | '_ \ / _' | |  | | | / __| __/ _ \| '_ ' _ \ / _ \ '__|${NONE}"
echo -e "${BLUE}|  _| | | | | | (_| | |__| |_| \__ \ || (_) | | | | | |  __/ |   ${NONE}"
echo -e "${BLUE}|_|   |_|_| |_|\__,_|\____\__,_|___/\__\___/|_| |_| |_|\___|_|   ${NONE}"                                                              
echo -e ${BLUE}__________________________________________________________________${NONE} 
echo -e ${BLUE}__________________________________________________________________${NONE} 
echo
echo "what do you want to search for:"
read search
echo
echo =========================================================================================
echo
grep $search CustomerDetails
echo
echo =========================================================================================
echo
echo -e "${RED}Do you wish to return to the Menu ?(y/n) ${NONE}"
read yesno
if  [[ $yesno = "y" ]]
	then 
	  ./Menu
else
	echo Goodbye
fi                                                          


